// demo/src/App.tsx
import { type ReactElement, useEffect, useState } from "react";
import { AccountChip } from "./AccountChip";
import { type EvmContext, resolveEvmContext } from "./chains/evm";
import { describeError } from "./connect";
import { TradingCard } from "./TradingCard";

const RESOLVE_RETRY_MS = 5_000;

/**
 * Resolves the network context, retrying on failure until stopped. Each
 * failure is surfaced through `onError` while the retries continue, because
 * the demo network comes back empty but reachable after a restart, which can
 * take up to a minute. Returns a stop function for effect cleanup.
 */
function retryingResolve<T>(
  resolve: () => Promise<T>,
  onResolved: (value: T) => void,
  onError: (message: string) => void,
): () => void {
  let stopped = false;
  let timer: number | undefined;
  function attempt(): void {
    resolve().then(
      (value) => {
        if (!stopped) onResolved(value);
      },
      (error: unknown) => {
        if (stopped) return;
        onError(describeError(error));
        timer = window.setTimeout(attempt, RESOLVE_RETRY_MS);
      },
    );
  }
  attempt();
  return () => {
    stopped = true;
    window.clearTimeout(timer);
  };
}

function App(): ReactElement {
  const [evmContext, setEvmContext] = useState<EvmContext | null>(null);
  const [evmError, setEvmError] = useState<string | null>(null);
  const [address, setAddress] = useState<`0x${string}` | null>(null);

  useEffect(
    () =>
      retryingResolve(
        resolveEvmContext,
        (context) => {
          setEvmContext(context);
          // Clear the failure once a retry lands, or the error line would
          // outlive the outage it reported.
          setEvmError(null);
        },
        setEvmError,
      ),
    [],
  );

  return (
    <main className="app">
      <header className="app-head">
        <h1>Mera Demo</h1>
        <AccountChip address={address} />
      </header>
      <TradingCard
        evm={evmContext}
        evmError={evmError}
        onAddressChange={setAddress}
      />
    </main>
  );
}

export { App };

// demos/vue/src/App.vue
<script setup lang="ts">
import {
  type AccountState,
  accountAddress,
  loadCachedAccount,
} from "@category-labs/mera-demo-shared/account";
import { describeError } from "@category-labs/mera-demo-shared/connect";
import {
  DEMO_CHAIN_ID,
  type EvmContext,
  resolveEvmContext,
} from "@category-labs/mera-demo-shared/network";
import { computed, onMounted, onUnmounted, ref, shallowRef } from "vue";
import AccountChip from "./AccountChip.vue";
import { RPC_URL } from "./config";
import TradingCard from "./TradingCard.vue";

const RESOLVE_RETRY_MS = 5_000;

const evm = shallowRef<EvmContext | null>(null);
const evmError = ref<string | null>(null);
const cached = loadCachedAccount();
const account = shallowRef<AccountState>(
  cached ? { status: "locked", ...cached } : { status: "none" },
);
const address = computed(() => accountAddress(account.value));

// Resolves the network context, retrying until it lands. Each failure shows
// while the retries continue, because the demo network comes back empty but
// reachable after a restart, which can take up to a minute.
let stopped = false;
let retryTimer: number | undefined;
async function resolveNetwork(): Promise<void> {
  try {
    evm.value = await resolveEvmContext({
      rpcUrl: RPC_URL,
      expectedChainId: DEMO_CHAIN_ID,
    });
    // Clear the failure once a retry lands, or the error line would outlive
    // the outage it reported.
    evmError.value = null;
  } catch (error) {
    if (stopped) return;
    evmError.value = describeError(error);
    retryTimer = window.setTimeout(
      () => void resolveNetwork(),
      RESOLVE_RETRY_MS,
    );
  }
}

onMounted(() => void resolveNetwork());
onUnmounted(() => {
  stopped = true;
  window.clearTimeout(retryTimer);
});
</script>

<template>
  <main class="app">
    <header class="app-head">
      <h1>mera demo <span class="framework-badge">Vue 3</span></h1>
      <AccountChip :address="address" :connected="evm !== null" />
    </header>
    <TradingCard v-model:account="account" :evm="evm" :evm-error="evmError" />
  </main>
</template>
