// demos/vue/src/ConnectPanel.vue
<script setup lang="ts">
import {
  type AccountMode,
  type ConnectedWallet,
  connect,
  describeError,
} from "@category-labs/mera-demo-shared/connect";
import {
  createMnemonic,
  isValidMnemonic,
} from "@category-labs/mera-demo-shared/hd";
import { computed, ref } from "vue";

type ConnectAction = "create" | "signin";

// The action a click started, and how far it has come: the passkey ceremony,
// then the awaited `onConnected`.
type ConnectBusy = {
  action: ConnectAction;
  phase: "passkey" | "opening";
};

/**
 * The connect area under the market data. Passkey mode offers explicit
 * create and sign-in actions; new passkeys are created under a fixed default
 * name. Vault mode imports or creates a phrase-backed account. The panel
 * stays busy until `onConnected` settles, so the parent can load the account
 * before this panel gives way to it. Mount with `:key="mode"` so switching
 * modes resets the local state.
 */
const props = defineProps<{
  mode: AccountMode;
  onConnected: (wallet: ConnectedWallet) => Promise<void>;
}>();

const secret = ref("");
const busy = ref<ConnectBusy | null>(null);
const error = ref<string | null>(null);

const trimmedSecret = computed(() => secret.value.trim());
const secretValid = computed(() => isValidMnemonic(trimmedSecret.value));

function generate(): void {
  secret.value = createMnemonic();
  error.value = null;
}

async function run(action: ConnectAction): Promise<void> {
  busy.value = { action, phase: "passkey" };
  error.value = null;
  try {
    const wallet = await connect(props.mode, action, secret.value);
    busy.value = { action, phase: "opening" };
    await props.onConnected(wallet);
  } catch (caught) {
    error.value = describeError(caught);
  } finally {
    busy.value = null;
  }
}

function actionLabel(action: ConnectAction, idle: string): string {
  if (busy.value === null || busy.value.action !== action) return idle;
  return busy.value.phase === "passkey"
    ? "Waiting for passkey…"
    : "Opening account…";
}
</script>

<template>
  <div class="connect-cta">
    <template v-if="mode === 'vault'">
      <p class="hint">
        The demo encrypts a recovery phrase in a vault that opens with the
        passkey. Generate a fresh one rather than importing a phrase that holds
        funds.
      </p>
      <div class="field">
        <span class="field-head">
          <label for="recovery-phrase">Recovery phrase</label>
          <button
            type="button"
            class="link small"
            :disabled="busy !== null"
            @click="generate"
          >
            Generate
          </button>
        </span>
        <input
          id="recovery-phrase"
          v-model="secret"
          placeholder="Generate a recovery phrase, or paste one from a wallet app"
          autocomplete="off"
          autocorrect="off"
          autocapitalize="off"
          spellcheck="false"
          :disabled="busy !== null"
        />
      </div>
      <p v-if="trimmedSecret.length > 0 && !secretValid" class="status error">
        That is not a valid recovery phrase.
      </p>
    </template>
    <div class="actions">
      <button
        type="button"
        class="btn primary"
        :disabled="busy !== null || (mode === 'vault' && !secretValid)"
        @click="run('create')"
      >
        {{ actionLabel("create", mode === "vault" ? "Open account" : "Create account") }}
      </button>
      <button
        type="button"
        class="btn"
        :disabled="busy !== null"
        @click="run('signin')"
      >
        {{ actionLabel("signin", "Sign in") }}
      </button>
    </div>
    <p v-if="error" class="status error">{{ error }}</p>
  </div>
</template>

// demo/src/ConnectPanel.tsx
import { type ReactElement, useState } from "react";
import {
  type AccountMode,
  type ConnectedWallet,
  connect,
  describeError,
} from "./connect";
import { createMnemonic, isValidMnemonic } from "./hd";

type ConnectPanelProps = {
  mode: AccountMode;
  onConnected: (wallet: ConnectedWallet) => void;
};

/**
 * The connect area under the market data. Passkey mode offers explicit
 * create and sign-in actions; new passkeys are created under a fixed default
 * name. Vault mode imports or creates a phrase-backed account. Mount with
 * `key={mode}` so switching modes resets the local state.
 */
function ConnectPanel({ mode, onConnected }: ConnectPanelProps): ReactElement {
  const [secret, setSecret] = useState("");
  const [busy, setBusy] = useState<"create" | "signin" | null>(null);
  const [error, setError] = useState<string | null>(null);

  const trimmedSecret = secret.trim();
  const secretValid = isValidMnemonic(trimmedSecret);

  function generate() {
    setSecret(createMnemonic());
    setError(null);
  }

  async function run(action: "create" | "signin") {
    setBusy(action);
    setError(null);
    try {
      onConnected(await connect(mode, action, secret));
    } catch (caught) {
      setError(describeError(caught));
    } finally {
      setBusy(null);
    }
  }

  if (mode === "vault") {
    return (
      <div className="connect-cta">
        <p className="hint">
          The demo encrypts a recovery phrase in a vault that opens with the
          passkey. Generate a fresh one rather than importing a phrase that
          holds funds.
        </p>
        <label className="field">
          <span className="field-head">
            Recovery phrase
            <button
              type="button"
              className="link small"
              onClick={generate}
              disabled={busy !== null}
            >
              Generate
            </button>
          </span>
          <input
            value={secret}
            placeholder="Generate a recovery phrase, or paste one from a wallet app"
            autoComplete="off"
            autoCorrect="off"
            autoCapitalize="off"
            spellCheck={false}
            onChange={(event) => setSecret(event.target.value)}
            disabled={busy !== null}
          />
        </label>
        {trimmedSecret.length > 0 && !secretValid && (
          <p className="status error">That is not a valid recovery phrase.</p>
        )}
        <div className="actions">
          <button
            type="button"
            className="btn primary"
            onClick={() => void run("create")}
            disabled={busy !== null || !secretValid}
          >
            {busy === "create" ? "Waiting for passkey…" : "Open account"}
          </button>
          <button
            type="button"
            className="btn"
            onClick={() => void run("signin")}
            disabled={busy !== null}
          >
            {busy === "signin" ? "Waiting for passkey…" : "Sign in"}
          </button>
        </div>
        {error && <p className="status error">{error}</p>}
      </div>
    );
  }

  return (
    <div className="connect-cta">
      <div className="actions">
        <button
          type="button"
          className="btn primary"
          onClick={() => void run("create")}
          disabled={busy !== null}
        >
          {busy === "create" ? "Waiting for passkey…" : "Create account"}
        </button>
        <button
          type="button"
          className="btn"
          onClick={() => void run("signin")}
          disabled={busy !== null}
        >
          {busy === "signin" ? "Waiting for passkey…" : "Sign in"}
        </button>
      </div>
      {error && <p className="status error">{error}</p>}
    </div>
  );
}

export { ConnectPanel };
